name: ML Pipeline Básico

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Ejecutar tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
